apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiraturbo
  labels:
    app: jiraturbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jiraturbo
  template:
    metadata:
      labels:
        app: jiraturbo
    spec:
      containers:
        - image: ading1977/jiraturbo
          imagePullPolicy: IfNotPresent
          name: jiraturbo
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jiraturbo
  labels:
    app: jiraturbo
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: tcp-jiraturbo
  selector:
    app: jiraturbo
