apiVersion: v1
kind: Service
metadata:
  name: csv-to-dif-target
  namespace: turbointegrations
  labels:
    app: csv-to-dif-app
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: csv-to-dif-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-to-dif
  namespace: turbointegrations
spec:
  selector:
    matchLabels:
      environment: nonprod
      team: integration
      app: csv-to-dif-app
      version: 1.0.0
  template:
    metadata:
      labels:
        environment: nonprod
        team: integration
        app: csv-to-dif-app
        version: 1.0.0
    spec:
      containers:
        - image: turbointegrations/csv-to-dif:1.0.1
          imagePullPolicy: IfNotPresent
          name: csv-to-dif
          ports:
          - containerPort: 8081
          envFrom:
            - secretRef:
                name: dif-csv-location-info
          volumeMounts:
            - name: config
              mountPath: /opt/turbonomic/config
      volumes:
        - name: config
          configMap:
            name: csv-to-dif-config
      restartPolicy: Always